librari-jsf/src/main/java/lab/librari/jsf/HelloBean.java
package lab.librari.jsf;

import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

// JavaBean == POJO = Plain Old Java Object
@ManagedBean(name="helloBean")
@ApplicationScoped
public class HelloBean {


    private int count = 0;

    public String getMessage(){
        return "Hello from HelloBean class :)";
    }

    public int getCount() {
        return ++count;
    }
}

librari-jsf/src/main/java/lab/librari/jsf/PublishersBean.java
package lab.librari.jsf;

import lab.librari.model.Book;
import lab.librari.model.Publisher;
import lab.librari.service.api.BrowsingService;
import lab.librari.service.impl.BrowsingServiceImpl;

import javax.faces.bean.ManagedBean;
import java.util.List;

@ManagedBean
public class PublishersBean {

    private BrowsingService bs = new BrowsingServiceImpl();

    private long publisherId;

    public List<Publisher> getPublishers(){
        return bs.getPublishers();
    }

    public List<Book> getBooks(){
        return bs.getBooksForPublisher(publisherId);
    }

    public long getPublisherId() {
        return publisherId;
    }

    public void setPublisherId(long publisherId) {
        this.publisherId = publisherId;
    }
}

librari-jsf/src/main/webapp/jsf/books.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

<h:body>

    <ui:composition template="template.xhtml">
        <ui:define name="title">
            Books list
        </ui:define>
        <ui:define name="content">
            <f:metadata>
                <f:viewParam
                        name="publisherId"
                        value="#{publishersBean.publisherId}"
                        />
            </f:metadata>

            <h:dataTable value="#{publishersBean.books}" var="b">
                <h:column>
                    <f:facet name="header">
                        Title
                    </f:facet>
                    <h:outputText value="#{b.title}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Author
                    </f:facet>
                    <h:outputText value="#{b.author}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Price
                    </f:facet>
                    <h:outputText value="#{b.price}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Cover
                    </f:facet>
                    <h:graphicImage value="#{b.cover}"/>
                </h:column>
            </h:dataTable>
        </ui:define>
    </ui:composition>

</h:body>

</html>

librari-jsf/src/main/webapp/jsf/hello.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<f:view>
    <h:outputLabel value="#{helloBean.message}"/>
    <br/>
    <h:outputText value="Count value = #{helloBean.count}"/>
</f:view>
</html>

librari-jsf/src/main/webapp/jsf/publishers.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">


<h:body>

    <ui:composition template="template.xhtml">
        <ui:define name="title">
            Publishers list
        </ui:define>
        <ui:define name="content">
            <h:dataTable value="#{publishersBean.publishers}" var="p">
                <h:column>
                    <f:facet name="header">
                        Name
                    </f:facet>
                    <h:link value="#{p.name}" outcome="books">
                         <f:param name="publisherId" value="#{p.id}"/>
                    </h:link>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Logo
                    </f:facet>
                    <h:graphicImage value="#{p.logoImage}"/>
                </h:column>
            </h:dataTable>
        </ui:define>

    </ui:composition>

</h:body>

</html>

librari-jsf/src/main/webapp/jsf/template.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

<h:head>
    <title>Librari JSF</title>
    <h:outputStylesheet library="css" name="style.css" />
    <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet"/>
</h:head>
<h:body>
    <header>
        <h1>Librari</h1>
        <h2><ui:insert name="title">TODO set title</ui:insert> </h2>
        <h3></h3>
    </header>
    <section>
        <ui:insert name="content">
            No content
        </ui:insert>
    </section>

</h:body>

</html>